const data2 = [
  {
    id: 1,
    name: "Daffi Glossup",
    unit: "Hope International University",
    age: 1,
    pronoun: "Non-binary",
    experience: "GMC",
    profileScore: 1,
    reviews: 1,
    interview: "Media Manager I",
  },
  {
    id: 2,
    name: "Emilee Kilfedder",
    unit: "Technological",
    age: 2,
    pronoun: "Female",
    experience: "Eagle",
    profileScore: 2,
    reviews: 2,
    interview: "Senior Sales Associate",
  },
  {
    id: 3,
    name: "Robina Lent",
    unit: "Stillman College",
    age: 3,
    pronoun: "Female",
    experience: "Pontiac",
    profileScore: 3,
    reviews: 3,
    interview: "Director of Sales",
  },
  {
    id: 4,
    name: "Lief Farron",
    unit: "Cornell University",
    age: 4,
    pronoun: "Male",
    experience: "Cadillac",
    profileScore: 4,
    reviews: 4,
    interview: "Payment Adjustment",
  },
  {
    id: 5,
    name: "Bond Moon",
    unit: "Wesleyan University",
    age: 5,
    pronoun: "Male",
    experience: "Hyundai",
    profileScore: 5,
    reviews: 5,
    interview: "Health Coach I",
  },
  {
    id: 6,
    name: "Nathanael Gregon",
    unit: "Southern College",
    age: 6,
    pronoun: "Male",
    experience: "Ram",
    profileScore: 6,
    reviews: 6,
    interview: "Geological Engineer",
  },
  {
    id: 7,
    name: "Vallie Killock",
    unit: "Universidade Federal",
    age: 7,
    pronoun: "Female",
    experience: "Chrysler",
    profileScore: 7,
    reviews: 7,
    interview: "Actuary",
  },
  {
    id: 8,
    name: "Derward Penhearow",
    unit: "Institut Armand-Frappier",
    age: 8,
    pronoun: "Male",
    experience: "Mercury",
    profileScore: 8,
    reviews: 8,
    interview: "Data Coordinator",
  },
  {
    id: 9,
    name: "Trudi Keegan",
    unit: "Anna Maria College",
    age: 9,
    pronoun: "Bigender",
    experience: "Maserati",
    profileScore: 9,
    reviews: 9,
    interview: "Legal Assistant",
  },
  {
    id: 10,
    name: "Annabella Peltzer",
    unit: "Manipur University",
    age: 10,
    pronoun: "Genderfluid",
    experience: "Volvo",
    profileScore: 10,
    reviews: 10,
    interview: "Human",
  },
];
export default data2;