const data = [
  {
    id: 1,
    first_name: "Amata",
    age: 2000,
    work: "Subcontractor",
    progress: 1,
    gender: "Female",
    time: "6:42:50",
  },
  {
    id: 2,
    first_name: "Josee",
    age: 2002,
    work: "Estimator",
    progress: 2,
    gender: "Female",
    time: "14:45:28",
  },
  {
    id: 3,
    first_name: "Jessika",
    age: 1990,
    work: "Estimator",
    progress: 3,
    gender: "Female",
    time: "23:02:54",
  },
  {
    id: 4,
    first_name: "Jacquenette",
    age: 2012,
    work: "Engineer",
    progress: 4,
    gender: "Female",
    time: "8:18:48",
  },
  {
    id: 5,
    first_name: "Casie",
    age: 2001,
    work: "Estimator",
    progress: 5,
    gender: "Female",
    time: "3:48:11",
  },
  {
    id: 6,
    first_name: "Bobette",
    age: 1992,
    work: "Construction Foreman",
    progress: 6,
    gender: "Female",
    time: "5:08:46",
  },
  {
    id: 7,
    first_name: "Patten",
    age: 1992,
    work: "Construction Worker",
    progress: 7,
    gender: "Male",
    time: "2:03:07",
  },
  {
    id: 8,
    first_name: "Currey",
    age: 2001,
    work: "Subcontractor",
    progress: 8,
    gender: "Male",
    time: "6:23:04",
  },
  {
    id: 9,
    first_name: "Joyce",
    age: 1998,
    work: "Estimator",
    progress: 9,
    gender: "Female",
    time: "6:39:29",
  },
  {
    id: 10,
    first_name: "Loy",
    age: 2009,
    work: "Architect",
    progress: 10,
    gender: "Male",
    time: "16:21:09",
  },
  {
    id: 11,
    first_name: "Claus",
    age: 2009,
    work: "Construction Worker",
    progress: 11,
    gender: "Male",
    time: "17:06:44",
  },
  {
    id: 12,
    first_name: "Alleyn",
    age: 2009,
    work: "Supervisor",
    progress: 12,
    gender: "Male",
    time: "18:36:38",
  },
  {
    id: 13,
    first_name: "Gelya",
    age: 2006,
    work: "Engineer",
    progress: 13,
    gender: "Female",
    time: "12:28:00",
  },
  {
    id: 14,
    first_name: "Hasty",
    age: 1994,
    work: "Subcontractor",
    progress: 14,
    gender: "Male",
    time: "11:12:00",
  },
  {
    id: 15,
    first_name: "Shayla",
    age: 2010,
    work: "Estimator",
    progress: 15,
    gender: "Female",
    time: "19:50:50",
  },
  {
    id: 16,
    first_name: "Kelly",
    age: 2001,
    work: "Supervisor",
    progress: 16,
    gender: "Female",
    time: "20:50:22",
  },
  {
    id: 17,
    first_name: "Bradan",
    age: 2009,
    work: "Subcontractor",
    progress: 17,
    gender: "Male",
    time: "10:48:14",
  },
  {
    id: 18,
    first_name: "Constantin",
    age: 2008,
    work: "Construction Expeditor",
    progress: 18,
    gender: "Male",
    time: "12:42:01",
  },
  {
    id: 19,
    first_name: "Iris",
    age: 2006,
    work: "Engineer",
    progress: 19,
    gender: "Female",
    time: "16:20:07",
  },
  {
    id: 20,
    first_name: "Ainsley",
    age: 2004,
    work: "Surveyor",
    progress: 20,
    gender: "Female",
    time: "10:51:40",
  },
  {
    id: 21,
    first_name: "Sylvester",
    age: 1997,
    work: "Construction Manager",
    progress: 21,
    gender: "Male",
    time: "22:47:07",
  },
  {
    id: 22,
    first_name: "Fletch",
    age: 1996,
    work: "Construction Expeditor",
    progress: 22,
    gender: "Male",
    time: "13:42:02",
  },
  {
    id: 23,
    first_name: "Keary",
    age: 2010,
    work: "Construction Worker",
    progress: 23,
    gender: "Male",
    time: "9:46:12",
  },
  {
    id: 24,
    first_name: "Reinhold",
    age: 2012,
    work: "Construction Expeditor",
    progress: 24,
    gender: "Male",
    time: "9:01:34",
  },
  {
    id: 25,
    first_name: "Berk",
    age: 2012,
    work: "Estimator",
    progress: 25,
    gender: "Male",
    time: "22:48:11",
  },
  {
    id: 26,
    first_name: "Jessee",
    age: 1992,
    work: "Engineer",
    progress: 26,
    gender: "Male",
    time: "1:30:23",
  },
  {
    id: 27,
    first_name: "Hastie",
    age: 2009,
    work: "Construction Expeditor",
    progress: 27,
    gender: "Male",
    time: "5:58:56",
  },
  {
    id: 28,
    first_name: "Gloriane",
    age: 2006,
    work: "Construction Foreman",
    progress: 28,
    gender: "Female",
    time: "5:41:13",
  },
  {
    id: 29,
    first_name: "Marcile",
    age: 2008,
    work: "Surveyor",
    progress: 29,
    gender: "Female",
    time: "6:36:23",
  },
  {
    id: 30,
    first_name: "Nealson",
    age: 1990,
    work: "Construction Manager",
    progress: 30,
    gender: "Male",
    time: "14:17:37",
  },
  {
    id: 31,
    first_name: "Norina",
    age: 2004,
    work: "Estimator",
    progress: 31,
    gender: "Female",
    time: "1:34:14",
  },
  {
    id: 32,
    first_name: "Fairfax",
    age: 1992,
    work: "Construction Manager",
    progress: 32,
    gender: "Male",
    time: "13:25:01",
  },
  {
    id: 33,
    first_name: "Jenna",
    age: 2012,
    work: "Engineer",
    progress: 33,
    gender: "Female",
    time: "22:46:33",
  },
  {
    id: 34,
    first_name: "Maynard",
    age: 2011,
    work: "Subcontractor",
    progress: 34,
    gender: "Male",
    time: "6:52:41",
  },
  {
    id: 35,
    first_name: "Sybyl",
    age: 1993,
    work: "Surveyor",
    progress: 35,
    gender: "Female",
    time: "6:07:43",
  },
  {
    id: 36,
    first_name: "Bea",
    age: 1998,
    work: "Construction Manager",
    progress: 36,
    gender: "Female",
    time: "15:01:16",
  },
  {
    id: 37,
    first_name: "Wood",
    age: 1996,
    work: "Project Manager",
    progress: 37,
    gender: "Male",
    time: "14:36:05",
  },
  {
    id: 38,
    first_name: "Christel",
    age: 1999,
    work: "Estimator",
    progress: 38,
    gender: "Female",
    time: "3:17:08",
  },
  {
    id: 39,
    first_name: "Roanne",
    age: 2012,
    work: "Electrician",
    progress: 39,
    gender: "Female",
    time: "1:55:09",
  },
  {
    id: 40,
    first_name: "Conroy",
    age: 2007,
    work: "Construction Manager",
    progress: 40,
    gender: "Male",
    time: "13:03:15",
  },
  {
    id: 41,
    first_name: "Son",
    age: 1993,
    work: "Surveyor",
    progress: 41,
    gender: "Male",
    time: "13:34:19",
  },
  {
    id: 42,
    first_name: "Damiano",
    age: 2012,
    work: "Estimator",
    progress: 42,
    gender: "Male",
    time: "0:21:07",
  },
  {
    id: 43,
    first_name: "Hank",
    age: 2007,
    work: "Estimator",
    progress: 43,
    gender: "Male",
    time: "9:37:31",
  },
  {
    id: 44,
    first_name: "Reinald",
    age: 2009,
    work: "Project Manager",
    progress: 44,
    gender: "Male",
    time: "0:15:00",
  },
  {
    id: 45,
    first_name: "Gavra",
    age: 2010,
    work: "Construction Manager",
    progress: 45,
    gender: "Female",
    time: "2:41:03",
  },
  {
    id: 46,
    first_name: "Boote",
    age: 2004,
    work: "Construction Manager",
    progress: 46,
    gender: "Male",
    time: "5:27:20",
  },
  {
    id: 47,
    first_name: "Clareta",
    age: 2000,
    work: "Engineer",
    progress: 47,
    gender: "Female",
    time: "21:34:48",
  },
  {
    id: 48,
    first_name: "Krista",
    age: 2002,
    work: "Subcontractor",
    progress: 48,
    gender: "Female",
    time: "8:16:21",
  },
  {
    id: 49,
    first_name: "Waylon",
    age: 2006,
    work: "Construction Foreman",
    progress: 49,
    gender: "Male",
    time: "14:42:59",
  },
  {
    id: 50,
    first_name: "Cassandry",
    age: 1994,
    work: "Subcontractor",
    progress: 50,
    gender: "Female",
    time: "17:03:49",
  },
  {
    id: 51,
    first_name: "Travus",
    age: 1998,
    work: "Estimator",
    progress: 51,
    gender: "Male",
    time: "13:41:29",
  },
  {
    id: 52,
    first_name: "Valeda",
    age: 2010,
    work: "Electrician",
    progress: 52,
    gender: "Female",
    time: "23:46:53",
  },
  {
    id: 53,
    first_name: "Geraldine",
    age: 2001,
    work: "Engineer",
    progress: 53,
    gender: "Female",
    time: "0:00:47",
  },
  {
    id: 54,
    first_name: "Waldemar",
    age: 2008,
    work: "Construction Manager",
    progress: 54,
    gender: "Male",
    time: "15:17:59",
  },
  {
    id: 55,
    first_name: "Gasper",
    age: 2012,
    work: "Subcontractor",
    progress: 55,
    gender: "Male",
    time: "21:22:53",
  },
  {
    id: 56,
    first_name: "Dallis",
    age: 2000,
    work: "Construction Worker",
    progress: 56,
    gender: "Male",
    time: "18:33:51",
  },
  {
    id: 57,
    first_name: "Mahmoud",
    age: 1996,
    work: "Supervisor",
    progress: 57,
    gender: "Male",
    time: "14:32:01",
  },
  {
    id: 58,
    first_name: "Mack",
    age: 2011,
    work: "Construction Foreman",
    progress: 58,
    gender: "Male",
    time: "1:31:19",
  },
  {
    id: 59,
    first_name: "Branden",
    age: 1963,
    work: "Construction Worker",
    progress: 59,
    gender: "Male",
    time: "1:46:31",
  },
  {
    id: 60,
    first_name: "Milena",
    age: 1995,
    work: "Supervisor",
    progress: 60,
    gender: "Female",
    time: "0:39:59",
  },
  {
    id: 61,
    first_name: "Luciana",
    age: 2012,
    work: "Engineer",
    progress: 61,
    gender: "Female",
    time: "19:52:43",
  },
  {
    id: 62,
    first_name: "Ivonne",
    age: 2004,
    work: "Supervisor",
    progress: 62,
    gender: "Female",
    time: "23:16:48",
  },
  {
    id: 63,
    first_name: "Donica",
    age: 2008,
    work: "Construction Expeditor",
    progress: 63,
    gender: "Female",
    time: "12:20:11",
  },
  {
    id: 64,
    first_name: "Jessalin",
    age: 1997,
    work: "Surveyor",
    progress: 64,
    gender: "Female",
    time: "3:26:16",
  },
  {
    id: 65,
    first_name: "Corabel",
    age: 2007,
    work: "Estimator",
    progress: 65,
    gender: "Female",
    time: "11:17:10",
  },
  {
    id: 66,
    first_name: "Archaimbaud",
    age: 2006,
    work: "Engineer",
    progress: 66,
    gender: "Male",
    time: "23:35:00",
  },
  {
    id: 67,
    first_name: "Aarika",
    age: 1997,
    work: "Supervisor",
    progress: 67,
    gender: "Female",
    time: "23:22:52",
  },
  {
    id: 68,
    first_name: "Magnum",
    age: 2001,
    work: "Construction Foreman",
    progress: 68,
    gender: "Male",
    time: "2:39:28",
  },
  {
    id: 69,
    first_name: "Melantha",
    age: 2011,
    work: "Estimator",
    progress: 69,
    gender: "Female",
    time: "7:59:59",
  },
  {
    id: 70,
    first_name: "Julissa",
    age: 2003,
    work: "Project Manager",
    progress: 70,
    gender: "Female",
    time: "14:42:18",
  },
  {
    id: 71,
    first_name: "Saxe",
    age: 2006,
    work: "Engineer",
    progress: 71,
    gender: "Male",
    time: "18:32:27",
  },
  {
    id: 72,
    first_name: "Beverlie",
    age: 1992,
    work: "Estimator",
    progress: 72,
    gender: "Female",
    time: "23:17:23",
  },
  {
    id: 73,
    first_name: "Jennette",
    age: 1993,
    work: "Construction Worker",
    progress: 73,
    gender: "Female",
    time: "5:19:24",
  },
  {
    id: 74,
    first_name: "Eugenia",
    age: 1987,
    work: "Construction Manager",
    progress: 74,
    gender: "Female",
    time: "9:40:39",
  },
  {
    id: 75,
    first_name: "Bernadene",
    age: 2005,
    work: "Project Manager",
    progress: 75,
    gender: "Female",
    time: "0:18:39",
  },
  {
    id: 76,
    first_name: "Estele",
    age: 1995,
    work: "Engineer",
    progress: 76,
    gender: "Female",
    time: "13:35:18",
  },
  {
    id: 77,
    first_name: "Linell",
    age: 2006,
    work: "Estimator",
    progress: 77,
    gender: "Female",
    time: "9:48:42",
  },
  {
    id: 78,
    first_name: "Vin",
    age: 1997,
    work: "Subcontractor",
    progress: 78,
    gender: "Male",
    time: "16:12:14",
  },
  {
    id: 79,
    first_name: "Lemmie",
    age: 1999,
    work: "Construction Worker",
    progress: 79,
    gender: "Male",
    time: "1:12:43",
  },
  {
    id: 80,
    first_name: "Anderea",
    age: 2008,
    work: "Engineer",
    progress: 80,
    gender: "Female",
    time: "7:04:18",
  },
  {
    id: 81,
    first_name: "Donelle",
    age: 2005,
    work: "Architect",
    progress: 81,
    gender: "Female",
    time: "14:10:37",
  },
  {
    id: 82,
    first_name: "Rolando",
    age: 1998,
    work: "Architect",
    progress: 82,
    gender: "Male",
    time: "15:42:03",
  },
  {
    id: 83,
    first_name: "Vivie",
    age: 1996,
    work: "Construction Worker",
    progress: 83,
    gender: "Female",
    time: "6:59:36",
  },
  {
    id: 84,
    first_name: "Gayelord",
    age: 1996,
    work: "Supervisor",
    progress: 84,
    gender: "Male",
    time: "3:04:02",
  },
  {
    id: 85,
    first_name: "Gib",
    age: 1997,
    work: "Construction Manager",
    progress: 85,
    gender: "Male",
    time: "12:55:51",
  },
  {
    id: 86,
    first_name: "Karen",
    age: 1997,
    work: "Electrician",
    progress: 86,
    gender: "Female",
    time: "7:56:33",
  },
  {
    id: 87,
    first_name: "Morissa",
    age: 1997,
    work: "Project Manager",
    progress: 87,
    gender: "Female",
    time: "13:53:32",
  },
  {
    id: 88,
    first_name: "Billy",
    age: 2005,
    work: "Construction Worker",
    progress: 88,
    gender: "Female",
    time: "13:42:31",
  },
  {
    id: 89,
    first_name: "Anselma",
    age: 2006,
    work: "Construction Expeditor",
    progress: 89,
    gender: "Female",
    time: "2:23:49",
  },
  {
    id: 90,
    first_name: "Jimmie",
    age: 2011,
    work: "Construction Manager",
    progress: 90,
    gender: "Male",
    time: "11:27:59",
  },
  {
    id: 91,
    first_name: "Barnabe",
    age: 2011,
    work: "Construction Worker",
    progress: 91,
    gender: "Male",
    time: "23:21:51",
  },
  {
    id: 92,
    first_name: "Dalila",
    age: 2005,
    work: "Construction Foreman",
    progress: 92,
    gender: "Female",
    time: "0:17:34",
  },
  {
    id: 93,
    first_name: "Coralyn",
    age: 1993,
    work: "Engineer",
    progress: 93,
    gender: "Female",
    time: "13:41:23",
  },
  {
    id: 94,
    first_name: "Gunther",
    age: 2005,
    work: "Construction Expeditor",
    progress: 94,
    gender: "Male",
    time: "14:24:53",
  },
  {
    id: 95,
    first_name: "Ransell",
    age: 1994,
    work: "Project Manager",
    progress: 95,
    gender: "Male",
    time: "18:11:23",
  },
  {
    id: 96,
    first_name: "Carolann",
    age: 2010,
    work: "Supervisor",
    progress: 96,
    gender: "Female",
    time: "10:55:32",
  },
  {
    id: 97,
    first_name: "Elfreda",
    age: 2006,
    work: "Estimator",
    progress: 97,
    gender: "Female",
    time: "5:08:35",
  },
  {
    id: 98,
    first_name: "Devland",
    age: 2002,
    work: "Construction Manager",
    progress: 98,
    gender: "Male",
    time: "10:47:15",
  },
  {
    id: 99,
    first_name: "Celestine",
    age: 2005,
    work: "Construction Expeditor",
    progress: 99,
    gender: "Female",
    time: "22:50:48",
  },
  {
    id: 100,
    first_name: "Lindy",
    age: 2009,
    work: "Construction Expeditor",
    progress: 100,
    gender: "Male",
    time: "21:04:32",
  },
];

export default data;
