const data = [
  {
    id: 1,
    first_name: "Tamqrah",
    last_name: "Earle",
    age: 1,
    work: "Surveyor",
    progress: 1,
  },
  {
    id: 2,
    first_name: "Karol",
    last_name: "Tetla",
    age: 2,
    work: "Engineer",
    progress: 2,
  },
  {
    id: 3,
    first_name: "Eimile",
    last_name: "Rigney",
    age: 3,
    work: "Project Manager",
    progress: 3,
  },
  {
    id: 4,
    first_name: "Cheston",
    last_name: "Trencher",
    age: 4,
    work: "Construction Manager",
    progress: 4,
  },
  {
    id: 5,
    first_name: "Opaline",
    last_name: "Netherclift",
    age: 5,
    work: "Project Manager",
    progress: 5,
  },
  {
    id: 6,
    first_name: "Danell",
    last_name: "Abatelli",
    age: 6,
    work: "Architect",
    progress: 6,
  },
  {
    id: 7,
    first_name: "Gwenneth",
    last_name: "Bittlestone",
    age: 7,
    work: "Construction Foreman",
    progress: 7,
  },
  {
    id: 8,
    first_name: "Dame",
    last_name: "Hayford",
    age: 8,
    work: "Construction Manager",
    progress: 8,
  },
  {
    id: 9,
    first_name: "Julee",
    last_name: "Btham",
    age: 9,
    work: "Construction Foreman",
    progress: 9,
  },
  {
    id: 10,
    first_name: "Kalil",
    last_name: "Saintsbury",
    age: 10,
    work: "Supervisor",
    progress: 10,
  },
  {
    id: 11,
    first_name: "Penny",
    last_name: "Gadd",
    age: 11,
    work: "Construction Expeditor",
    progress: 11,
  },
  {
    id: 12,
    first_name: "Cristobal",
    last_name: "Thurske",
    age: 12,
    work: "Electrician",
    progress: 12,
  },
  {
    id: 13,
    first_name: "Terry",
    last_name: "Blumsom",
    age: 13,
    work: "Construction Expeditor",
    progress: 13,
  },
  {
    id: 14,
    first_name: "Coralie",
    last_name: "Skase",
    age: 14,
    work: "Construction Expeditor",
    progress: 14,
  },
  {
    id: 15,
    first_name: "Cull",
    last_name: "Snalom",
    age: 15,
    work: "Subcontractor",
    progress: 15,
  },
  {
    id: 16,
    first_name: "Ora",
    last_name: "Wathen",
    age: 16,
    work: "Subcontractor",
    progress: 16,
  },
  {
    id: 17,
    first_name: "Zena",
    last_name: "Guinness",
    age: 17,
    work: "Surveyor",
    progress: 17,
  },
  {
    id: 18,
    first_name: "Vincenz",
    last_name: "Pretious",
    age: 18,
    work: "Supervisor",
    progress: 18,
  },
  {
    id: 19,
    first_name: "Burk",
    last_name: "Reggiani",
    age: 19,
    work: "Construction Worker",
    progress: 19,
  },
  {
    id: 20,
    first_name: "Wilton",
    last_name: "Boycott",
    age: 20,
    work: "Construction Worker",
    progress: 20,
  },
  {
    id: 21,
    first_name: "Maitilde",
    last_name: "Gauchier",
    age: 21,
    work: "Electrician",
    progress: 21,
  },
  {
    id: 22,
    first_name: "Shanie",
    last_name: "Samme",
    age: 22,
    work: "Engineer",
    progress: 22,
  },
  {
    id: 23,
    first_name: "John",
    last_name: "Curton",
    age: 23,
    work: "Engineer",
    progress: 23,
  },
  {
    id: 24,
    first_name: "Millard",
    last_name: "Creavan",
    age: 24,
    work: "Architect",
    progress: 24,
  },
  {
    id: 25,
    first_name: "Darcie",
    last_name: "Bywaters",
    age: 25,
    work: "Engineer",
    progress: 25,
  },
  {
    id: 26,
    first_name: "Demetrius",
    last_name: "Birtwell",
    age: 26,
    work: "Construction Worker",
    progress: 26,
  },
  {
    id: 27,
    first_name: "Sonnnie",
    last_name: "McGeachie",
    age: 27,
    work: "Construction Expeditor",
    progress: 27,
  },
  {
    id: 28,
    first_name: "Thalia",
    last_name: "Cortese",
    age: 28,
    work: "Construction Expeditor",
    progress: 28,
  },
  {
    id: 29,
    first_name: "Babita",
    last_name: "Buckenhill",
    age: 29,
    work: "Project Manager",
    progress: 29,
  },
  {
    id: 30,
    first_name: "Lonee",
    last_name: "Lampkin",
    age: 30,
    work: "Project Manager",
    progress: 30,
  },
  {
    id: 31,
    first_name: "Viole",
    last_name: "Harold",
    age: 31,
    work: "Project Manager",
    progress: 31,
  },
  {
    id: 32,
    first_name: "Walliw",
    last_name: "Hendren",
    age: 32,
    work: "Construction Worker",
    progress: 32,
  },
  {
    id: 33,
    first_name: "Felicdad",
    last_name: "Atterley",
    age: 33,
    work: "Project Manager",
    progress: 33,
  },
  {
    id: 34,
    first_name: "Fanchette",
    last_name: "Buggy",
    age: 34,
    work: "Subcontractor",
    progress: 34,
  },
  {
    id: 35,
    first_name: "Bailey",
    last_name: "Chainey",
    age: 35,
    work: "Electrician",
    progress: 35,
  },
  {
    id: 36,
    first_name: "Timothea",
    last_name: "Ciccetti",
    age: 36,
    work: "Construction Expeditor",
    progress: 36,
  },
  {
    id: 37,
    first_name: "Suzie",
    last_name: "Fullilove",
    age: 37,
    work: "Architect",
    progress: 37,
  },
  {
    id: 38,
    first_name: "Emmey",
    last_name: "Mulcaster",
    age: 38,
    work: "Construction Manager",
    progress: 38,
  },
  {
    id: 39,
    first_name: "Curr",
    last_name: "Pouck",
    age: 39,
    work: "Subcontractor",
    progress: 39,
  },
  {
    id: 40,
    first_name: "Ginger",
    last_name: "Devonald",
    age: 40,
    work: "Construction Manager",
    progress: 40,
  },
  {
    id: 41,
    first_name: "Harrietta",
    last_name: "Prophet",
    age: 41,
    work: "Construction Foreman",
    progress: 41,
  },
  {
    id: 42,
    first_name: "Bert",
    last_name: "Travers",
    age: 42,
    work: "Construction Worker",
    progress: 42,
  },
  {
    id: 43,
    first_name: "Agnes",
    last_name: "Trigg",
    age: 43,
    work: "Architect",
    progress: 43,
  },
  {
    id: 44,
    first_name: "Marvin",
    last_name: "Chilvers",
    age: 44,
    work: "Construction Expeditor",
    progress: 44,
  },
  {
    id: 45,
    first_name: "Perri",
    last_name: "Wooller",
    age: 45,
    work: "Subcontractor",
    progress: 45,
  },
  {
    id: 46,
    first_name: "Philbert",
    last_name: "Meaker",
    age: 46,
    work: "Estimator",
    progress: 46,
  },
  {
    id: 47,
    first_name: "Gaelan",
    last_name: "Chinn",
    age: 47,
    work: "Electrician",
    progress: 47,
  },
  {
    id: 48,
    first_name: "Elianore",
    last_name: "Pillman",
    age: 48,
    work: "Architect",
    progress: 48,
  },
  {
    id: 49,
    first_name: "Dale",
    last_name: "Fairhurst",
    age: 49,
    work: "Supervisor",
    progress: 49,
  },
  {
    id: 50,
    first_name: "Kain",
    last_name: "Popham",
    age: 50,
    work: "Construction Expeditor",
    progress: 50,
  },
  {
    id: 51,
    first_name: "Alla",
    last_name: "Pedroni",
    age: 51,
    work: "Electrician",
    progress: 51,
  },
  {
    id: 52,
    first_name: "Keven",
    last_name: "Mattea",
    age: 52,
    work: "Estimator",
    progress: 52,
  },
  {
    id: 53,
    first_name: "Angus",
    last_name: "Jentgens",
    age: 53,
    work: "Subcontractor",
    progress: 53,
  },
  {
    id: 54,
    first_name: "Bourke",
    last_name: "Kaufman",
    age: 54,
    work: "Supervisor",
    progress: 54,
  },
  {
    id: 55,
    first_name: "Louella",
    last_name: "Date",
    age: 55,
    work: "Engineer",
    progress: 55,
  },
  {
    id: 56,
    first_name: "Dugald",
    last_name: "Moncreif",
    age: 56,
    work: "Architect",
    progress: 56,
  },
  {
    id: 57,
    first_name: "Morgen",
    last_name: "MacGibbon",
    age: 57,
    work: "Project Manager",
    progress: 57,
  },
  {
    id: 58,
    first_name: "Herbie",
    last_name: "McAreavey",
    age: 58,
    work: "Engineer",
    progress: 58,
  },
  {
    id: 59,
    first_name: "Jeremiah",
    last_name: "Snowball",
    age: 59,
    work: "Construction Manager",
    progress: 59,
  },
  {
    id: 60,
    first_name: "Neddie",
    last_name: "Rainer",
    age: 60,
    work: "Architect",
    progress: 60,
  },
  {
    id: 61,
    first_name: "Cathryn",
    last_name: "Denziloe",
    age: 61,
    work: "Construction Manager",
    progress: 61,
  },
  {
    id: 62,
    first_name: "Pippa",
    last_name: "Legier",
    age: 62,
    work: "Construction Foreman",
    progress: 62,
  },
  {
    id: 63,
    first_name: "Hamil",
    last_name: "Baseke",
    age: 63,
    work: "Architect",
    progress: 63,
  },
  {
    id: 64,
    first_name: "Abbey",
    last_name: "Efford",
    age: 64,
    work: "Project Manager",
    progress: 64,
  },
  {
    id: 65,
    first_name: "Immanuel",
    last_name: "Vany",
    age: 65,
    work: "Subcontractor",
    progress: 65,
  },
  {
    id: 66,
    first_name: "Hendrika",
    last_name: "Slimming",
    age: 66,
    work: "Electrician",
    progress: 66,
  },
  {
    id: 67,
    first_name: "Britte",
    last_name: "Baillie",
    age: 67,
    work: "Subcontractor",
    progress: 67,
  },
  {
    id: 68,
    first_name: "Maridel",
    last_name: "Elnough",
    age: 68,
    work: "Surveyor",
    progress: 68,
  },
  {
    id: 69,
    first_name: "Nial",
    last_name: "Kew",
    age: 69,
    work: "Construction Manager",
    progress: 69,
  },
  {
    id: 70,
    first_name: "Irma",
    last_name: "Murrells",
    age: 70,
    work: "Supervisor",
    progress: 70,
  },
  {
    id: 71,
    first_name: "Carley",
    last_name: "Crickett",
    age: 71,
    work: "Architect",
    progress: 71,
  },
  {
    id: 72,
    first_name: "Carlee",
    last_name: "Roscamp",
    age: 72,
    work: "Construction Manager",
    progress: 72,
  },
  {
    id: 73,
    first_name: "Farrel",
    last_name: "Treske",
    age: 73,
    work: "Subcontractor",
    progress: 73,
  },
  {
    id: 74,
    first_name: "Con",
    last_name: "Richemont",
    age: 74,
    work: "Engineer",
    progress: 74,
  },
  {
    id: 75,
    first_name: "Lizette",
    last_name: "Kliesl",
    age: 75,
    work: "Subcontractor",
    progress: 75,
  },
  {
    id: 76,
    first_name: "Charlene",
    last_name: "Oughtright",
    age: 76,
    work: "Surveyor",
    progress: 76,
  },
  {
    id: 77,
    first_name: "Daryn",
    last_name: "Saphin",
    age: 77,
    work: "Engineer",
    progress: 77,
  },
  {
    id: 78,
    first_name: "Carolina",
    last_name: "Wombwell",
    age: 78,
    work: "Electrician",
    progress: 78,
  },
  {
    id: 79,
    first_name: "Jonell",
    last_name: "Linham",
    age: 79,
    work: "Surveyor",
    progress: 79,
  },
  {
    id: 80,
    first_name: "Prent",
    last_name: "Prozescky",
    age: 80,
    work: "Estimator",
    progress: 80,
  },
  {
    id: 81,
    first_name: "Avis",
    last_name: "Fridaye",
    age: 81,
    work: "Architect",
    progress: 81,
  },
  {
    id: 82,
    first_name: "Brnaba",
    last_name: "Dow",
    age: 82,
    work: "Construction Manager",
    progress: 82,
  },
  {
    id: 83,
    first_name: "Emmott",
    last_name: "Dyble",
    age: 83,
    work: "Engineer",
    progress: 83,
  },
  {
    id: 84,
    first_name: "Johnna",
    last_name: "Gillespie",
    age: 84,
    work: "Construction Foreman",
    progress: 84,
  },
  {
    id: 85,
    first_name: "Aaron",
    last_name: "Hiddsley",
    age: 85,
    work: "Engineer",
    progress: 85,
  },
  {
    id: 86,
    first_name: "Cherilyn",
    last_name: "Russam",
    age: 86,
    work: "Construction Foreman",
    progress: 86,
  },
  {
    id: 87,
    first_name: "Jud",
    last_name: "Hubbard",
    age: 87,
    work: "Architect",
    progress: 87,
  },
  {
    id: 88,
    first_name: "Bianca",
    last_name: "Godby",
    age: 88,
    work: "Surveyor",
    progress: 88,
  },
  {
    id: 89,
    first_name: "Hesther",
    last_name: "Spilsted",
    age: 89,
    work: "Architect",
    progress: 89,
  },
  {
    id: 90,
    first_name: "Kimmy",
    last_name: "MacMakin",
    age: 90,
    work: "Subcontractor",
    progress: 90,
  },
  {
    id: 91,
    first_name: "Vanny",
    last_name: "Baldinotti",
    age: 91,
    work: "Construction Worker",
    progress: 91,
  },
  {
    id: 92,
    first_name: "Michaella",
    last_name: "Rowan",
    age: 92,
    work: "Estimator",
    progress: 92,
  },
  {
    id: 93,
    first_name: "Purcell",
    last_name: "Kale",
    age: 93,
    work: "Surveyor",
    progress: 93,
  },
  {
    id: 94,
    first_name: "Kimmy",
    last_name: "Brammar",
    age: 94,
    work: "Project Manager",
    progress: 94,
  },
  {
    id: 95,
    first_name: "Calli",
    last_name: "Saterthwait",
    age: 95,
    work: "Estimator",
    progress: 95,
  },
  {
    id: 96,
    first_name: "Phaidra",
    last_name: "Order",
    age: 96,
    work: "Construction Expeditor",
    progress: 96,
  },
  {
    id: 97,
    first_name: "Charita",
    last_name: "Gabbitus",
    age: 97,
    work: "Supervisor",
    progress: 97,
  },
  {
    id: 98,
    first_name: "Ogdan",
    last_name: "Diegan",
    age: 98,
    work: "Subcontractor",
    progress: 98,
  },
  {
    id: 99,
    first_name: "Benny",
    last_name: "Ropking",
    age: 99,
    work: "Supervisor",
    progress: 99,
  },
  {
    id: 100,
    first_name: "Madelyn",
    last_name: "Mickleborough",
    age: 100,
    work: "Surveyor",
    progress: 100,
  },
];

export default data;